language: node_js
node_js:
  - "lts/*"

sudo: false

# install:
#   - npm install
# script:
#   - npm test

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
