# travis-ci.org

language: node_js
node_js:
  - "lts/*"

sudo: false

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
